name: queue_it_library
repository: https://github.com/sharpsan/queue_it_library

packages:
  - queue_it
  - flutter_queue_it

ignore:
  - "**/example"

scripts:
  analyze:
    exec: dart analyze .

  clean:
    exec: flutter clean

  pub_get:
    exec: flutter pub get

  pub_outdated:
    exec: flutter pub outdated

  pub_upgrade:
    exec: flutter pub upgrade

  run_tests:
    exec: flutter test
    packageFilters:
      ignore: [flutter_queue_it]
