name: queue_it_library
repository: https://github.com/sharpsan/queue_it_library

packages:
  - queue_it
  - flutter_queue_it

scripts:
  analyze:
    exec: dart analyze .

  flutter_clean:
    exec: flutter clean

  flutter_pub_get:
    exec: flutter pub get
