name: queue_it_library
repository: https://github.com/sharpsan/queue_it_library

packages:
  - queue_it
  - flutter_queue_it
  - flutter_queue_it/example

sdkPath: .fvm/flutter_sdk

scripts:
  analyze:
    exec: dart analyze .
