name: flutter_queue_it
description: "Flutter integration for QueueIt.  Provides a widget that automatically rebuilds when the queue is updated."
version: 0.9.0
repository: https://github.com/sharpsan/queue_it_library

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  queue_it: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
