name: easy_queue
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/sharpsan/easy_queue_library/easy_queue

environment:
  sdk: ^3.0.2

dependencies:
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
